/**
 * utils/transcript.js — YouTube AI Assistant v4.5
 * Extracts captions from YouTube's timedtext API.
 *
 * Exposes: window.TranscriptExtractor
 *   .extract()            → { segments, langCode, language, isAutoGenerated } | { error }
 *   .getVideoTitle()      → string
 *   .getVideoDescription()→ string
 *   .getChannelName()     → string
 */

const TranscriptExtractor = (() => {
  "use strict";

  // ── DOM Helpers ──────────────────────────────────────────────────────────────

  function getVideoTitle() {
    return (
      document.querySelector("ytd-watch-metadata h1 yt-formatted-string")?.textContent ||
      document.querySelector("h1.ytd-video-primary-info-renderer yt-formatted-string")?.textContent ||
      document.querySelector(".ytd-watch-metadata h1")?.textContent ||
      document.title?.replace(" - YouTube", "") ||
      ""
    ).trim();
  }

  function getVideoDescription() {
    return (
      document.querySelector("#description-inline-expander #snippet-text")?.textContent ||
      document.querySelector("ytd-text-inline-expander #snippet-text")?.textContent ||
      document.querySelector("#description yt-formatted-string")?.textContent ||
      document.querySelector("ytd-expander #content yt-attributed-string")?.textContent ||
      ""
    ).slice(0, 500).trim();
  }

  function getChannelName() {
    return (
      document.querySelector("ytd-channel-name #channel-name yt-formatted-string")?.textContent ||
      document.querySelector("#channel-name .ytd-channel-name yt-formatted-string")?.textContent ||
      document.querySelector("ytd-video-owner-renderer ytd-channel-name yt-formatted-string")?.textContent ||
      ""
    ).trim();
  }

  // ── Caption Track Discovery ──────────────────────────────────────────────────

  /**
   * Parse ytInitialPlayerResponse from inline <script> tags.
   * Returns caption tracks array or null.
   */
  function getCaptionTracks() {
    try {
      // Method 1: search inline scripts for ytInitialPlayerResponse
      for (const script of document.querySelectorAll("script")) {
        const t = script.textContent;
        if (!t.includes("captionTracks")) continue;

        // Try a JSON block extraction
        const idx = t.indexOf("ytInitialPlayerResponse");
        if (idx === -1) continue;
        const start = t.indexOf("{", idx);
        if (start === -1) continue;

        // Balanced brace extraction (more reliable than regex for large objects)
        let depth = 0, end = start;
        for (; end < Math.min(start + 500000, t.length); end++) {
          if (t[end] === "{") depth++;
          else if (t[end] === "}") { depth--; if (depth === 0) break; }
        }

        try {
          const data   = JSON.parse(t.slice(start, end + 1));
          const tracks = data?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
          if (tracks?.length) return tracks;
        } catch (_) {}
      }

      // Method 2: ytInitialPlayerResponse may be a global variable
      if (typeof ytInitialPlayerResponse !== "undefined") {
        const tracks = ytInitialPlayerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
        if (tracks?.length) return tracks;
      }
    } catch (_) {}

    return null;
  }

  /**
   * Pick the best caption track.
   * Priority: manual English > any manual > ASR English > any ASR
   */
  function selectBestTrack(tracks) {
    if (!tracks?.length) return null;
    const manual = tracks.filter(t => !t.kind || t.kind !== "asr");
    const asr    = tracks.filter(t => t.kind === "asr");

    const engManual = manual.find(t => t.languageCode?.startsWith("en"));
    if (engManual) return { track: engManual, isAuto: false };
    if (manual.length) return { track: manual[0], isAuto: false };

    const engAsr = asr.find(t => t.languageCode?.startsWith("en"));
    if (engAsr) return { track: engAsr, isAuto: true };
    if (asr.length) return { track: asr[0], isAuto: true };

    // Fallback: just use first track
    return { track: tracks[0], isAuto: true };
  }

  // ── Fetch & Parse ────────────────────────────────────────────────────────────

  async function fetchCaptionXML(baseUrl) {
    // Try srv3 first (word-level timing), fall back to plain
    for (const fmt of ["srv3", "srv1", ""]) {
      const url = fmt ? `${baseUrl}&fmt=${fmt}` : baseUrl;
      try {
        const res = await fetch(url);
        if (res.ok) return { xml: await res.text(), fmt };
      } catch (_) {}
    }
    throw new Error("Could not fetch caption data from YouTube");
  }

  function parseSrv3(doc) {
    // srv3: <timedtext><body><p t="ms" d="ms"><s>word</s>…</p>…</body></timedtext>
    const nodes = doc.querySelectorAll("p");
    if (!nodes.length) return null;
    const segments = [];
    for (const p of nodes) {
      const startMs = parseFloat(p.getAttribute("t") || 0);
      const durMs   = parseFloat(p.getAttribute("d") || 2000);
      const text    = Array.from(p.querySelectorAll("s")).map(s => s.textContent).join(" ")
                    || p.textContent;
      const clean   = decodeEntities(text).trim();
      if (clean) segments.push({ text: clean, start: startMs / 1000, duration: durMs / 1000 });
    }
    return segments.length ? segments : null;
  }

  function parseSrv1(doc) {
    // srv1: <transcript><text start="s" dur="s">…</text>…</transcript>
    const nodes = doc.querySelectorAll("text");
    if (!nodes.length) return null;
    const segments = [];
    for (const node of nodes) {
      const start    = parseFloat(node.getAttribute("start") || 0);
      const duration = parseFloat(node.getAttribute("dur")   || 2);
      const clean    = decodeEntities(node.textContent).trim();
      if (clean) segments.push({ text: clean, start, duration });
    }
    return segments.length ? segments : null;
  }

  function parseCaptionXML(xml) {
    const parser = new DOMParser();
    const doc    = parser.parseFromString(xml, "text/xml");

    // Try srv3, then srv1
    return parseSrv3(doc) || parseSrv1(doc) || null;
  }

  function decodeEntities(str) {
    return String(str)
      .replace(/&amp;/g,  "&")
      .replace(/&lt;/g,   "<")
      .replace(/&gt;/g,   ">")
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g,  "'")
      .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
      .replace(/\n/g, " ")
      .replace(/\s+/g, " ")
      .trim();
  }

  // ── Public: extract ──────────────────────────────────────────────────────────

  async function extract() {
    const vid = new URLSearchParams(location.search).get("v");
    if (!vid) return { error: "No video ID in URL" };

    const tracks = getCaptionTracks();
    if (!tracks?.length) {
      return { error: "No captions available for this video" };
    }

    const selection = selectBestTrack(tracks);
    if (!selection) return { error: "No usable caption track found" };

    const { track, isAuto } = selection;

    try {
      const { xml }  = await fetchCaptionXML(track.baseUrl);
      const segments = parseCaptionXML(xml);

      if (!segments?.length) {
        return { error: "Caption data is empty or unparseable" };
      }

      return {
        segments,
        langCode:        track.languageCode || "en",
        language:        track.name?.simpleText || track.languageCode || "Unknown",
        isAutoGenerated: isAuto,
      };
    } catch (err) {
      return { error: `Transcript error: ${err.message}` };
    }
  }

  return { extract, getVideoTitle, getVideoDescription, getChannelName };
})();
